services:
  item-service:
    image: mikkelhv/4semitemservice:latest
    container_name: itemService
    ports:
      - "5001:8080"
    environment:
      - MongoConnectionString=${MongoConnectionString}
      - DatabaseName=ItemDB
      - CollectionName=items
      - LOKI_URL=${LOKI_URL}
    networks:
      - gron-network

  user-service:
    image: mikkelhv/4semuserservice:latest
    container_name: userService
    ports:
      - "5002:8080"
    environment:
      - MongoConnectionString=${MongoConnectionString}
      - DatabaseName=UserDB
      - CollectionName=users
      - LOKI_URL=${LOKI_URL}
    networks:
      - gron-network

  auth-service:
    image: mikkelhv/4semauthservice:latest
    container_name: authService
    ports:
      - "5003:8080"
    environment:
      - UserServiceEndpoint=${UserServiceEndpoint}
      - VaultURL=${VaultURL}
      - VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID}
      - LOKI_URL=${LOKI_URL}
    networks:
      - gron-network

networks:
  gron-network:
    name: gron-network

